LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LIBBLUETOOTH_BASE = /opt/android
LIBBLUETOOTH_LDLIBS = -L$(SYSROOT)/usr/lib -L$(LIBBLUETOOTH_BASE)/libs/$(TARGET_ARCH_ABI) -lbluetooth
LIBBLUETOOTH_CPPFLAGS = -I$(LIBBLUETOOTH_BASE)/include

LOCAL_LDLIBS += $(LIBBLUETOOTH_LDLIBS)
LOCAL_CFLAGS += $(LIBBLUETOOTH_CPPFLAGS)
LOCAL_MODULE := bluebridge
LOCAL_SRC_FILES := bluebridge.c

include $(BUILD_SHARED_LIBRARY)
